name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: clang++ Source.cpp -o text_tablica
    - name: Test
      run: ./text_tablica tests/in/input.txt output.txt && cmp output.txt tests/out/input.txt
